namespace AntiDupl.NET.Core.Enums
{
    public enum Error
    {
        Ok = 0,
        Unknown = 1,
        AccessDenied = 2,
        InvalidPointer = 3,
        InvalidFileFormat = 4,
        InvalidPathType = 5,
        InvalidOptionsType = 6,
        InvalidFileType = 7,
        InvalidSortType = 8,
        InvalidGlobalActionType = 9,
        InvalidThreadId = 10,
        InvalidStartPosition = 11,
        OutputBufferIsTooSmall = 12,
        FileIsNotExists = 13,
        CantOpenFile = 14,
        CantCreateFile = 15,
        CantReadFile = 16,
        CantWriteFile = 17,
        InvalidFileName = 18,
        InvalidLocalActionType = 19,
        InvalidTargetType = 20,
        InvalidIndex = 21,
        ZeroTarget = 22,
        PathTooLong = 23,
        CantLoadImage = 24,
        InvalidBitmap = 25,
        InvalidThreadType = 26,
        InvalidActionEnableType = 27,
        InvalidParameterCombination = 28,
        InvalidRenameCurrentType = 29,
        InvalidInfoType = 30,
        InvalidGroupId = 31,
        InvalidSelectionType = 32,
    }
}
